////////////////////////////////////////////////////////////
//
// Handle defining macros for lua registration and 
// declaration of lua API functions
//
////////////////////////////////////////////////////////////

#pragma once

// ========================================================================
// Lua Function Macro Declarations
// 
// Declare your lua API functions by picking your desired system macro
// and then declaring a "LUA_FUNCTION" entry for your new function.
// The "LUA_FUNCTION" macro will take 2 parameters: the function 
// signature in lua and the function signature in CPP
// ========================================================================

#define LUA_ENGINE_LIBRARY_FUNCTIONS \
LUA_FUNCTION( testFunct, LuaFunction_TestFunct )


// ========================================================================
// Lua Library Macro Declarations
// 
// A "Lua Library" is just a way to group API functions (Ex: for the 
// "Engine" library, functions are accessed as "Engine.function()"). 
// Declare your library below in the LUA_FUNCTION_LIBRARIES macro 
// by creating a new "LUA_LIBRARY" entry. The "LUA_LIBRARY" 
// takes 2 parameters: the library name and the macro 
// representing all of the library's API functions which 
// should be declared above in this file.
// ========================================================================

#define LUA_FUNCTION_LIBRARIES \
LUA_LIBRARY( Engine, LUA_ENGINE_LIBRARY_FUNCTIONS )


// =============================================
// Autogenerated lua API function delcarations
// =============================================

#define LUA_FUNCTION( luaFunctName, cppFunctName ) int cppFunctName( struct lua_State* luaState );
LUA_ENGINE_LIBRARY_FUNCTIONS
#undef LUA_FUNCTION